name: app_maker
description: A powerful app & game maker using Flutter
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  provider: ^6.0.5
  path_provider: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
